services:
  # Ollama server com configuração mais robusta
  ollama:
    image: ollama/ollama:latest
    container_name: mit-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 2G

  # MIT Tracking Agent (sem depender do ollama-setup)
  mit-orchestrator:
    build: .
    container_name: mit-python-orchestrator
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:3b
      - PYTHONUNBUFFERED=1
      - CREW_VERBOSE=true
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    restart: unless-stopped

# Volume para persistir modelos do Ollama
volumes:
  ollama_data: